### ISSUE TITLE
Calendar Refresh Button

### ISSUE THREAD

**Issue by JM-Lemmi** [frereit/react-calendar#21]
pull the new ical without having to reload the whole app?

**Comment by JM-Lemmi** [comment]
The browser refresh resets the selected week. Und lädt das Javascript neu herunter, soweit ich das sehe

**Comment by frereit** [comment]
Javascript sollte cashed sein. Ja, die ausgewählte Woche geht verloren, aber dann würde ich eher vorschlagen die ausgewählte Woche in der URL zu speichern
